name = "FunctionalDataUtils"
uuid = "ac2312be-67e5-11e8-0517-53290e6fe864"
authors = ["Rene Donner <code@donner.at>"]
version = "0.2.1"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
FunctionalData = "3307bf92-67e5-11e8-014e-27eee38d7b4d"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
